#!/bin/bash

# Check if Docker is installed
if ! command -v docker &> /dev/null
then
    echo "Docker is not installed. Please install it from: https://docs.docker.com/get-docker/"
    read -p "Press any key to continue..."  # Wait for user input
    exit 1
fi

# Check if Docker is running
if (! docker info > /dev/null 2>&1); then
    echo "Docker is not running. Starting Docker Desktop..."
    open -a Docker
    echo "Please wait for Docker to start..."
    
    # Wait until Docker is running
    while (! docker info > /dev/null 2>&1); do
        sleep 2
    done
    echo "Docker is now running."
fi

# Navigate to the directory where the script is located
cd "$(dirname "${BASH_SOURCE[0]}")/.."

IMAGE_NAME="cropcounter"

# Check if the Docker image exists
if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == "" ]]; then
    echo "Image not found. Building the Docker image..."
    docker build -t $IMAGE_NAME .
else
    echo "Image already exists. Removing the old image..."
    docker rmi $IMAGE_NAME -f
    echo "Building the Docker image..."
    docker build -t $IMAGE_NAME .
fi

exit 0