#!/bin/bash

# Navigate to the directory where the script is located
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Create a virtual environment using Python 3
python3 -m venv venv

# Activate the virtual environment
source venv/bin/activate

# Install dependencies from requirements.txt
pip3 install -r requirements.txt

exit 0